# Generated by Django 4.2.23 on 2025-07-13 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations import RunPython
import django.db.models.fields.json # Make sure this is imported for JSONField

class Migration(migrations.Migration):

    initial = False # Set to False for subsequent migrations

    dependencies = [
        ('plag', '0001_initial'), # <--- IMPORTANT: Ensure this matches the previous migration's name
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use RunPython.noop if ai_probability_score already exists in the DB
        # This prevents Django from trying to add it again and throwing an error.
        RunPython.noop, # Placeholder for ai_probability_score if it's the problematic one

        # Add all the other missing fields to ScanLog
        migrations.AddField(
            model_name='scanlog',
            name='ai_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='burstiness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='top_words',
            field=django.db.models.fields.json.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='text_snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='document_name',
            field=models.CharField(default='Unnamed Document', max_length=255),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents/'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        # If 'fail_type' was also missing from your DB (even though it's in 0001_initial), add it here too:
        # migrations.AddField(
        #     model_name='scanlog',
        #     name='fail_type',
        #     field=models.CharField(blank=True, choices=[('H', 'HTTP error'), ('C', 'No content candidates found (initial scan) or matched (post processing)'), ('E', 'Internal processing error'), ('I', 'Skipped/Ignored')], max_length=1, null=True),
        # ),
    ]