# Generated by Django 4.2.23 on 2025-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='intake',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
